package com.laudoecia.api.domain;

import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(CamposDoLaudo.class)
public abstract class CamposDoLaudo_ {

	public static volatile SingularAttribute<CamposDoLaudo, String> campo23;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo22;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo21;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo20;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo7;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo27;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo6;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo26;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo9;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo25;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo8;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo24;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo29;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo28;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo1;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo3;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo2;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo5;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo4;
	public static volatile SingularAttribute<CamposDoLaudo, Long> codigo;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo30;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo34;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo33;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo32;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo31;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo38;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo37;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo36;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo35;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo39;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo41;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo40;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo45;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo44;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo43;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo42;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo49;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo48;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo47;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo46;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo52;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo51;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo50;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo12;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo11;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo10;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo16;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo15;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo14;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo13;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo19;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo18;
	public static volatile SingularAttribute<CamposDoLaudo, String> campo17;

	public static final String CAMPO23 = "campo23";
	public static final String CAMPO22 = "campo22";
	public static final String CAMPO21 = "campo21";
	public static final String CAMPO20 = "campo20";
	public static final String CAMPO7 = "campo7";
	public static final String CAMPO27 = "campo27";
	public static final String CAMPO6 = "campo6";
	public static final String CAMPO26 = "campo26";
	public static final String CAMPO9 = "campo9";
	public static final String CAMPO25 = "campo25";
	public static final String CAMPO8 = "campo8";
	public static final String CAMPO24 = "campo24";
	public static final String CAMPO29 = "campo29";
	public static final String CAMPO28 = "campo28";
	public static final String CAMPO1 = "campo1";
	public static final String CAMPO3 = "campo3";
	public static final String CAMPO2 = "campo2";
	public static final String CAMPO5 = "campo5";
	public static final String CAMPO4 = "campo4";
	public static final String CODIGO = "codigo";
	public static final String CAMPO30 = "campo30";
	public static final String CAMPO34 = "campo34";
	public static final String CAMPO33 = "campo33";
	public static final String CAMPO32 = "campo32";
	public static final String CAMPO31 = "campo31";
	public static final String CAMPO38 = "campo38";
	public static final String CAMPO37 = "campo37";
	public static final String CAMPO36 = "campo36";
	public static final String CAMPO35 = "campo35";
	public static final String CAMPO39 = "campo39";
	public static final String CAMPO41 = "campo41";
	public static final String CAMPO40 = "campo40";
	public static final String CAMPO45 = "campo45";
	public static final String CAMPO44 = "campo44";
	public static final String CAMPO43 = "campo43";
	public static final String CAMPO42 = "campo42";
	public static final String CAMPO49 = "campo49";
	public static final String CAMPO48 = "campo48";
	public static final String CAMPO47 = "campo47";
	public static final String CAMPO46 = "campo46";
	public static final String CAMPO52 = "campo52";
	public static final String CAMPO51 = "campo51";
	public static final String CAMPO50 = "campo50";
	public static final String CAMPO12 = "campo12";
	public static final String CAMPO11 = "campo11";
	public static final String CAMPO10 = "campo10";
	public static final String CAMPO16 = "campo16";
	public static final String CAMPO15 = "campo15";
	public static final String CAMPO14 = "campo14";
	public static final String CAMPO13 = "campo13";
	public static final String CAMPO19 = "campo19";
	public static final String CAMPO18 = "campo18";
	public static final String CAMPO17 = "campo17";

}

